const transactionData = [
  {
    id: "txn-001",
    name: "Emma Richardson",
    category: "Freelance Work",
    amount: 750000,
    date: "2024-08-18",
    type: "income",
    avatar: null,
  },
  {
    id: "txn-002",
    name: "Savory Bites Bistro",
    category: "Food & Dining",
    amount: -55000,
    date: "2024-08-18",
    type: "expense",
    avatar: null,
  },
  {
    id: "txn-003",
    name: "Daniel Carter",
    category: "Utilities",
    amount: -42000,
    date: "2024-08-18",
    type: "expense",
    avatar: null,
  },
  {
    id: "txn-004",
    name: "Sun Park",
    category: "Investments",
    amount: 12000.0,
    date: "2024-08-17",
    type: "income",
    avatar: null,
  },
  {
    id: "txn-005",
    name: "Urban Services Hub",
    category: "Transport",
    amount: -10000.0,
    date: "2024-08-17",
    type: "expense",
    avatar: null,
  },
  {
    id: "txn-006",
    name: "Freelance Payment",
    category: "Freelance Work",
    amount: 300000.0,
    date: "2024-08-16",
    type: "income",
    avatar: null,
  },
  {
    id: "txn-007",
    name: "Gym Membership",
    category: "Health & Fitness",
    amount: -60000.0,
    date: "2024-08-15",
    type: "expense",
    avatar: null,
  },
  {
    id: "txn-008",
    name: "Online Course",
    category: "Education",
    amount: -150000.0,
    date: "2024-08-14",
    type: "expense",
    avatar: null,
  },
];

export default transactionData;
